---

- name: install | download and extract claymore
  unarchive:
    src: "{{ claymore_download_url }}"
    dest: '/tmp'
    remote_src: yes
    creates: "/tmp/{{ claymore_tar_foldername }}"
    mode: 0644
#    owner: "{{ miner_user }}"
#    group: "{{ miner_group }}"

- name: install | set claymore binary file attributes
  file:
    path: "/tmp/{{ claymore_tar_foldername }}/ethdcrminer64"
    mode: 0755
    owner: "{{ miner_user }}"
    group: "{{ miner_group }}"

- name: install | create claymore install directory
  file:
    path: "{{ claymore_bin_path }}"
    state: 'directory'
    mode: 0755
    owner: "{{ miner_user }}"
    group: "{{ miner_group }}"

- name: install | move claymore extracted files to install directory
  synchronize:
    src: "/tmp/{{ claymore_tar_foldername }}/"
    dest: '/opt/claymore/'
    owner: yes
    group: yes
  delegate_to: "{{ inventory_hostname }}"

#- name: install | move claymore extracted files to install directory
#  copy:
#    remote_src: yes
#    src: "/tmp/{{ claymore_tar_foldername }}/*"
#    dest: '/opt/claymore/'
#    owner: "{{ miner_user }}"
#    group: "{{ miner_group }}"

#  "{{ claymore_bin_path }}"

#- name: chown claymore directory
#  file:
#    path: /opt/claymore_v10.0
#    state: directory
#    owner: miner
#    group: miner
#    mode: 0644
#    recurse: yes

#- name: add claymore startup file
#  template:
#    src: 'templates/start_miner.sh.j2'
#    dest: "{{ claymore_bin_path }}/start_miner.sh"
#    owner: "{{ miner_user }}"
#    group: "{{ miner_group }}"
#    mode: 0755

- name: install | add claymore epools file
  template:
    src: 'templates/epools.txt.j2'
    dest: "{{ claymore_bin_path }}/epools.txt"
    owner: "{{ miner_user }}"
    group: "{{ miner_group }}"
    mode: 0644
