---
- include_vars: wallet_vars.yml
- name: add miner group
  group:
    name: "{{ miner_group }}"
    state: 'present'

- name: add miner user
  user:
    name: "{{ miner_user }}"
    state: 'present'
    shell: '/bin/bash'
    groups: 'miner,video'
    append: 'yes'

- name: create claymore download directory
  file:
    path: "{{ claymore_bin_path }}"
    state: 'directory'
    mode: 0755
    owner: "{{ miner_user }}"
    group: "{{ miner_group }}"

- name: download and extract claymore
  unarchive:
    src: "{{ claymore_download_url }}"
    dest: "{{ claymore_bin_path }}"
    remote_src: yes
    owner: "{{ miner_user }}"
    group: "{{ miner_group }}"
    mode: 0644
    creates: "{{ claymore_bin_path }}/ethdcrminer64"

#- name: chown claymore directory
#  file:
#    path: /opt/claymore_v10.0
#    state: directory
#    owner: miner
#    group: miner
#    mode: 0644
#    recurse: yes

- name: set claymore binary file attributes
  file:
    path: "{{ claymore_bin_path }}/ethdcrminer64"
    mode: 0755
    owner: "{{ miner_user }}"
    group: "{{ miner_group }}"

#- name: add claymore startup file
#  template:
#    src: 'templates/start_miner.sh.j2'
#    dest: "{{ claymore_bin_path }}/start_miner.sh"
#    owner: "{{ miner_user }}"
#    group: "{{ miner_group }}"
#    mode: 0755

- name: add claymore epools file
  template:
    src: 'templates/epools.txt.j2'
    dest: "{{ claymore_bin_path }}/epools.txt"
    owner: "{{ miner_user }}"
    group: "{{ miner_group }}"
    mode: 0644
