---
- name: install | install sshpass
  yum:
    name: sshpass
    state: present

- name: install | download and extract claymore
  unarchive:
    src: "{{ claymore_download_url }}"
    dest: '/tmp'
    remote_src: yes
    creates: "/tmp/{{ claymore_tar_foldername }}"
    mode: 0755
    owner: "{{ miner_user }}"
    group: "{{ miner_group }}"
  register: unarchive_claymore

- name: install | set claymore_folder fact
  set_fact:
    claymore_folder: "/opt/claymore_{{ claymore_version }}"

- name: install | rename claymore folder
  shell:
    cmd: cp -r "/tmp/{{ claymore_tar_foldername }}" "{{ claymore_folder }}/"
  when: unarchive_claymore.changed

- name: install | set claymore binary file attributes
  file:
    path: "{{ claymore_folder }}/ethdcrminer64"
    mode: 0755
    owner: "{{ miner_user }}"
    group: "{{ miner_group }}"

- name: install | create claymore install directory
  file:
    path: "{{ claymore_folder }}"
    state: 'directory'
    mode: 0755
    owner: "{{ miner_user }}"
    group: "{{ miner_group }}"

## TODO: just extract to /opt/claymore/vers, and symlink
#- name: install | move claymore extracted files to install directory
#  synchronize:
#    src: "/tmp/{{ new_claymore_tar_foldername }}/"
#    dest: '/opt/claymore/'
#    owner: yes
#    group: yes
#  delegate_to: "{{ inventory_hostname }}"
#  when: unarchive_claymore.changed

- name: install | add claymore epools file
  template:
    src: 'templates/epools.txt.j2'
    dest: "{{ claymore_folder }}/epools.txt"
    owner: "{{ miner_user }}"
    group: "{{ miner_group }}"
    mode: 0644
