---
- include_vars: wallet_vars.yml

- name: include users tasks
  include_tasks: users.yml

- name: include install tasks
  include_tasks: install.yml

- name: include systemd tasks
  include_tasks: systemd.yml
