---
#- name: install burstcoin prereqs
#  apt:
#    name: "{{ item }}"
#  with_items:
#    - "openjdk-9-jre"
#    - "make"
#    - "gcc"

- name: configure docker
  include_role:
    name: docker

- name: include stats tasks
  include_tasks: stats.yml

#- name: include plotter tasks
#  include_tasks: plotter.yml

- name: include container tasks
  include_tasks: container.yml
