---
#- name: install burstcoin prereqs
#  apt:
#    name: "{{ item }}"
#  with_items:
#    - "openjdk-9-jre"
#    - "make"
#    - "gcc"

- name: configure docker
  include_role:
    name: docker

- name: include plotter.yml
  include_tasks: plotter.yml

- name: include miner.yml
  include_tasks: miner.yml

- name: Install sysstat
  apt:
    pkg: sysstat
    state: latest
    update_cache: yes

- name: Install iotop
  apt:
    pkg: iotop
    state: latest
    update_cache: yes

