---
#- name: install burstcoin prereqs
#  apt:
#    name: "{{ item }}"
#  with_items:
#    - "openjdk-9-jre"
#    - "make"
#    - "gcc"

- name: configure docker
  include_role:
    name: docker

- name: docker pull jertel/omdcct
  shell:
    cmd: 'docker pull jertel/omdcct'

- name: Install sysstat
  apt:
    pkg: sysstat
    state: latest
    update_cache: yes

- name: Install iotop
  apt:
    pkg: iotop
    state: latest
    update_cache: yes

# TODO: make sure external is mounted
# udev rules for persistent naming for USB
# mount external to docker
# git clone https://github.com/zurajm/burst-plotter  # the plotter
# docker build that ^
# instructions for plotting: docker run -it -v /media/plot:/mnt/burst <container id> -k <key> -d /mnt/burst/plots -x 1
