---
- name: create plot1 mount folder
  file:
    path: '/media/plots/plot1'
    state: 'directory'

- name: mount usb drive for creepminer
  mount:
    src: '/dev/sdb1'
    fstype: 'ext4'
    opts: 'defaults,nofail,x-systemd.device-timeout=10'
    path: '/media/plots/plot1'
    state: 'mounted'
