---
# tasks file for ansible_claymore

#sudo apt update
#sudo apt dist-upgrade

#package gcc
#wget -qO - http://repo.radeon.com/rocm/apt/debian/rocm.gpg.key | sudo apt-key add -
#sudo sh -c 'echo deb [arch=amd64] http://repo.radeon.com/rocm/apt/debian/ xenial main > /etc/apt/sources.list.d/rocm.list'
#sudo apt-get update

#sudo apt-get install libnuma-dev
#sudo apt-get install rocm-dkms
#sudo apt-get install rocm-dkms rocm-opencl
#sudo apt-get install rocm-opencl-dev
#sudo apt-get install rocm-dev

#sudo usermod -a -G video $LOGNAME

# wget https://raw.githubusercontent.com/bgaster/opencl-book-samples/master/src/Chapter_2/HelloWorld/HelloWorld.cpp
# wget https://raw.githubusercontent.com/bgaster/opencl-book-samples/master/src/Chapter_2/HelloWorld/HelloWorld.cl
# g++ -I /opt/rocm/opencl/include/ ./HelloWorld.cpp -o HelloWorld -L/opt/rocm/opencl/lib/x86_64 -lOpenCL
# ./HelloWorld
