---
- name: install ukuu repo
  apt_repository:
    repo: 'ppa:teejee2008/ppa'
- name: install ukuu
  apt:
    name: ukuu
- name: list installed kernels
  shell: "ukuu --list | grep Installed || true"
  register: install_kernel
  changed_when: false
- name: install needed kernel
  shell: "ukuu --install \"{{ kernel_version }}\""
  when: "not install_kernel.stdout|search(kernel_version)"
  register: install_needed_kernel
