---
- name: add miner group
  group:
    name: miner
    state: present
- name: add miner user
  user:
    name: miner
    state: present
    shell: /bin/bash
    groups: miner, video
    append: yes
- name: Install unzip
  apt:
    name: unzip
- name: Install xz-utils
  apt:
    name: xz-utils
- name: Install python-pip
  apt:
    name: python-pip
- name: Install pexpect
  pip:
    name: pexpect
- name: install ukuu repo
  apt_repository:
    repo: 'ppa:teejee2008/ppa'
- name: install ukuu
  apt:
    name: ukuu
- name: install libelf-dev for AMDGPU-PRO
  apt:
    name: libelf-dev
